# Generated by Django 3.2 on 2022-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
