# Generated by Django 3.2 on 2022-05-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220506_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventory',
            name='is_promotion',
        ),
        migrations.RemoveField(
            model_name='historicalinventory',
            name='promotional_price',
        ),
        migrations.RemoveField(
            model_name='historicalinventory',
            name='recent_purchase_price',
        ),
        migrations.RemoveField(
            model_name='historicalinventory',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='is_promotion',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='promotional_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='recent_purchase_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='max_selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='min_selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='recent_buying_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='max_selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='recent_buying_price',
            field=models.IntegerField(default=0),
        ),
    ]
