# Generated by Django 3.2 on 2022-05-10 05:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220507_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='phone_number_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
