# Generated by Django 3.2 on 2022-05-10 21:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220507_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='historicalcolor',
            name='code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
