# Generated by Django 3.2 on 2022-05-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220510_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pin_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='pin_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='vat_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
