# Generated by Django 3.2 on 2022-05-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220510_2134'),
        ('base', '0009_auto_20220514_1028'),
    ]

    operations = [
    ]
