# Generated by Django 3.2 on 2022-05-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_0007_auto_20220510_2134_0009_auto_20220514_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(default='#FF0000', max_length=70),
        ),
        migrations.AlterField(
            model_name='historicalcolor',
            name='code',
            field=models.CharField(default='#FF0000', max_length=70),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.customer'),
        ),
    ]
