# Generated by Django 3.2 on 2022-05-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220519_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesitem',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.product'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.product'),
        ),
    ]
