# Generated by Django 3.2 on 2022-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220522_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='stock_unit',
            field=models.CharField(default='Packages', max_length=120),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock_unit',
            field=models.CharField(default='Packages', max_length=120),
        ),
    ]
