# Generated by Django 3.2 on 2022-05-28 10:01

import base.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_auto_20220522_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreplenishment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='historicalreplenishment',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='historicalreplenishment',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='replenishment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='replenishment',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='replenishment',
            name='price_per_item',
        ),
        migrations.AlterField(
            model_name='historicalreplenishment',
            name='receipt_number',
            field=models.CharField(default=base.helper.generate_receipt, max_length=500),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='receipt_number',
            field=models.CharField(default=base.helper.generate_receipt, max_length=500),
        ),
        migrations.CreateModel(
            name='ReplenishmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_base_replenishmentitem_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.inventory')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_by_base_replenishmentitem_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('replenishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.replenishment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalReplenishmentItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.inventory')),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('replenishment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.replenishment')),
            ],
            options={
                'verbose_name': 'historical replenishment item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
