# Generated by Django 3.2 on 2022-05-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220521_1508'),
        ('base', '0013_auto_20220522_2126'),
    ]

    operations = [
    ]
