# Generated by Django 3.2 on 2022-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220528_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreplenishment',
            name='receipt_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='receipt_number',
            field=models.CharField(max_length=500),
        ),
    ]
