# Generated by Django 3.2 on 2022-05-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_merge_0013_auto_20220521_1508_0013_auto_20220522_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesitem',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.inventory'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.inventory'),
        ),
    ]
