# Generated by Django 3.2 on 2022-05-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220528_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishmentitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventory'),
        ),
        migrations.AlterField(
            model_name='replenishmentitem',
            name='replenishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.replenishment'),
        ),
    ]
