# Generated by Django 3.2 on 2022-05-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220524_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinventory',
            old_name='max_selling_price',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='max_selling_price',
            new_name='selling_price',
        ),
    ]
