# Generated by Django 3.2 on 2022-05-29 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_auto_20220528_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedinventory',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='damaged_by_base_damagedinventory_set', to=settings.AUTH_USER_MODEL, verbose_name='damaged by'),
        ),
        migrations.AlterField(
            model_name='historicaldamagedinventory',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='damaged by'),
        ),
    ]
