# Generated by Django 3.2 on 2022-05-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220529_1059'),
        ('base', '0017_auto_20220529_0020'),
    ]

    operations = [
    ]
