# Generated by Django 3.2 on 2022-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_merge_0016_auto_20220529_1059_0017_auto_20220529_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpromotion',
            name='promotion_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_price',
            field=models.IntegerField(default=0),
        ),
    ]
