# Generated by Django 3.2 on 2022-06-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220604_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replenishment',
            options={'ordering': ['-modified', '-created']},
        ),
    ]
