# Generated by Django 3.2 on 2022-05-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20220531_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
