# Generated by Django 3.2 on 2022-06-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_damagedinventory_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.supplier'),
        ),
        migrations.AlterField(
            model_name='historicaldamagedinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.supplier'),
        ),
    ]
