# Generated by Django 3.2 on 2022-06-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20220617_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='sales_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.salesitem'),
        ),
    ]
