# Generated by Django 3.2 on 2022-06-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20220622_2314'),
        ('base', '0025_auto_20220617_1635'),
    ]

    operations = [
    ]
