# Generated by Django 3.2 on 2022-08-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20220626_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsize',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size_type',
        ),
        migrations.AlterField(
            model_name='historicalsize',
            name='value',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productColor', to='base.color'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productFinish', to='base.finish'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productRange', to='base.range'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productSize', to='base.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
