# Generated by Django 3.2 on 2022-08-14 11:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20220813_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
