# Generated by Django 3.2 on 2022-08-27 10:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20220814_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='phone_number_1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='pin_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='vat_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number_1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pin_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
