# Generated by Django 3.2 on 2022-10-08 17:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20221002_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='cash_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='mpesa_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALY_PAID', 'PARTIALY_PAID'), ('FULLY_PAID', 'FULLY_PAID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='pending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='transaction_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CASH', 'CASH'), ('MPESA', 'MPESA')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cash_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mpesa_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALY_PAID', 'PARTIALY_PAID'), ('FULLY_PAID', 'FULLY_PAID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CASH', 'CASH'), ('MPESA', 'MPESA')], max_length=40, null=True),
        ),
    ]
