# Generated by Django 3.2 on 2022-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20221008_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALY_PAID', 'PARTIALY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALY_PAID', 'PARTIALY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
    ]
