# Generated by Django 3.2 on 2022-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20221009_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreplenishment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalreplenishment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALY_PAID', 'PARTIALY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalreplenishment',
            name='pending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALY_PAID', 'PARTIALY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='pending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
