# Generated by Django 3.2 on 2022-10-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20221010_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreplenishment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('FULLY_PAID', 'FULLY_PAID'), ('NOT_PAID', 'NOT_PAID')], max_length=20, null=True),
        ),
    ]
